---

- name: Installs nftables
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - nftables



- name: Enable NFTables
  service:
    name: nftables
    enabled: yes
    state: started
  notify:
    - systemctl daemon reload
  tags:
    - nftables



#/etc/nftables

# - name: Copy nftables-configuration directory for all.
#   ansible.builtin.file:
#     path: "/etc/nftables"
#     state: directory
#     owner: root
#     group: root
#     mode: 0755
#   become: true

- name: Copy nftables-configuration file for nodesweb.
  template:
    src: "templates/nftables_nodesweb.conf.j2"
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: 0744
  become: true
  notify:
    - restart nftables
  when: "'nodesweb' in group_names"

# - name: Copy filebeat-configuration file for bastion.
#   template:
#     src: "templates/nftables_bastion.conf.j2"
#     dest: /etc/nftables.conf
#     owner: root
#     group: root
#     mode: 0744
#   become: true
#   notify:
#     - restart nftables
#   when: "'bastions' in group_names"


- name: Copy nftables-configuration file for frontend.
  template:
    src: "templates/nftables_frontend.conf.j2"
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: 0744
  become: true
  notify:
    - restart nftables
  when: "'frontend' in group_names"


- name: Copy filebeat-configuration file for nodesdb .
  template:
    src: "templates/nftables_nodesdb.conf.j2"
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: 0744
  become: true
  notify:
    - restart nftables
  when: "'nodesdb' in group_names"

- name: restart nftables
  systemd:
    name: nftables
    state: restarted
    enabled: yes
