---

- name: "Install gnupg"
  ansible.builtin.apt:
    name: gnupg2
    update_cache: yes


- name: Adds repository key
  apt_key:
    url: https://repo.proxysql.com/ProxySQL/proxysql-2.7.x/repo_pub_key
    state: present

- name: Adds percona repositories
  apt_repository:
    repo: 'deb https://repo.proxysql.com/ProxySQL/proxysql-{{ proxysql_version }}.x/{{ ansible_distribution_release }} ./'
    state: present

- name: Installs proxysql & python-mysqldb
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - proxysql
    - python3-mysqldb

- name: Holds proxysql version
  dpkg_selections:
    name: proxysql
    selection: hold

- name: Installs mysql-common & client
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - mysql-common
    - default-mysql-client
