---

- name: Playbook of 00_all
  hosts:
    - all
  become: true
  roles:
    - role: '../roles/00_all'

- name: iscsiadm

  hosts:
    - nodes
  become: true
  roles:
    - { role: 'OndrejHome.iscsiadm' }

- name: iscsitarget

  hosts:
    - iscsitargets
  become: true
  roles:
    - { role: 'ondrejhome.targetcli' }
  vars:
    iscsi_targets:
      - wwn: 'iqn.1994-05.com.redhat:target'
        disks:
          - path: '/dev/vdb'
            name: 'disk01'
            type: 'block'
        initiators: "[ {% for host in groups['nodes'] %} '{{ hostvars[host][\"iscsi_initiator_name\"] }}', {% endfor %} ]"

- name: Connect  nodes to iSCSI target

  become: true
  hosts: 
    - nodes
  tags: iscsinodes
  tasks:
    - name: Discover iSCSI target
      shell: |
        iscsiadm -m discovery -t st -p 10.200.0.254
        iscsiadm -m discovery -t st -p 10.201.0.254
        iscsiadm -m node -l
    - name: Start iSCSI initiators on clients
      service:
        name: iscsid
        state: started

- name: Configure Multipath
  become: true
  hosts: nodes
  tags: mpio
  roles:
    - { role: '02_mpio_configure' }

- name: Playbook of Install Pacemaker
  become: true
  hosts: nodes
  tags: pacemaker
  roles:
    - { role: '03_pacemaker' }


- name: Playbook of Install iscsifensing
  become: true
  hosts: nodes
  tags: iscsifensing
  roles:
    - { role: '04_iscsifensing' }

- name: Install GFS2 and cLVM software
  become: true
  hosts: nodes
  roles:
    - { role: '05_gfs2_cluster' }    