---



# Установим gnupg для ключа репозитория

- name: "Install gnupg"
  apt:
    name: gnupg2
    update_cache: yes


- name: Install generally useful packages
  package:
    name:
      - tree
      - vim
      - less
      - screen
      - htop
      - ssl-cert
      - net-tools
    state: present



# добавим ключ репозитория

- name: Add PostgreSQL apt key
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present


## Добавим репозиторий

- name: Add PostgreSQL repository
  apt_repository:
    repo: deb https://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main
    state: present

# Установим Postgres

- name: Install PostgreSQL 
  apt:
    name:
      - "postgresql-{{ postgresql_major_version }}"
      - "postgresql-contrib-{{ postgresql_major_version }}"
      - "postgresql-client-{{ postgresql_major_version }}"
      - "postgresql-{{ postgresql_major_version }}-rum"
    update_cache: yes
    state: present

# Проверяем, что postgres на хосте ещё не инициализирован
- name: check init 
  stat:
    path: /var/lib/postgresql/{{ postgresql_major_version }}/main/pg_stat
  register: stat_result

# Выполняем удаление дефолтной базы

- name: Recursively remove directory postgres database
  ansible.builtin.file:
    path: "{{ postgresql_data_dir_base }}/{{ postgresql_major_version }}/main"
    state: absent
  when: stat_result.stat.exists


# Выполняем проверку что каталог дефолтной базы существует 

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: "{{ postgresql_data_dir_base }}/{{ postgresql_major_version }}/main"
    owner: "postgres"
    group: "postgres"
    mode: '0700'
    state: directory
  when: stat_result.stat.exists

- name: Disable auto creation of PostgreSQL clusters
  lineinfile:
    dest: "/etc/postgresql-common/createcluster.conf"
    line: "create_main_cluster = false" 
    regexp: ".*create_main_cluster.*"
  tags:
    - config

- name: systemctl disabled postgresql
  systemd:
    name: postgresql
    state: stopped
    enabled: false




  