---



# Установим gnupg для ключа репозитория

- name: "Install gnupg"
  apt:
    name: gnupg2
    update_cache: yes


- name: Install generally useful packages
  package:
    name:
      - tree
      - vim
      - less
      - screen
      - htop
      - ssl-cert
      - net-tools
    state: present



# добавим ключ репозитория

- name: Add PostgreSQL apt key
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present


## Добавим репозиторий

- name: Add PostgreSQL repository
  apt_repository:
    repo: deb https://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main
    state: present

# Установим Postgres

- name: Install PostgreSQL 
  apt:
    name:
      - "postgresql-{{ postgresql_major_version }}"
      - "postgresql-contrib-{{ postgresql_major_version }}"
      - "postgresql-client-{{ postgresql_major_version }}"
    update_cache: yes
    state: present

# Проверяем, что postgres на хосте ещё не инициализирован
- name: check init 
  stat:
    path: /var/lib/postgresql/{{ postgresql_major_version }}/main/pg_stat
  register: stat_result


- name: Install postgresql-common
  package:
    name: postgresql-common
    default_release: "{{ ansible_lsb.codename }}-{{ pgdg_repo | default('pgdg') }}"
    state: present

- name: Disable auto creation of PostgreSQL clusters
  lineinfile:
    dest: "/etc/postgresql-common/createcluster.conf"
    line: "create_main_cluster = false" 
    regexp: ".*create_main_cluster.*"
  tags:
    - config

- name: systemctl disabled postgresql
  systemd:
    name: postgresql
    state: stopped
    enabled: false

# # Выполняем инициализацию postgres
# - name: initialization setup
#   shell: /usr/lib/postgresql/16/bin/initdb
#   when: not stat_result.stat.exists
#   become: true
  
# # Запускаем postgresql
# - name: enable and start service
#   service:
#     name: postgresql
#     state: started
#     enabled: true


- name: Copy pgpass from template
  template:
    src: templates/postgres_pgpass
    dest: "/var/lib/postgresql/{{ postgresql_major_version }}-{{ postgresql_cluster_name }}.pgpass"
    mode: 0600
    owner: "postgres"
    group: "postgres"


  