---

- name: Playbook of 01_Nginx
  hosts:
    - all
  become: true
  roles:
    - role: '../roles/01_Nginx'

  vars_files:
    - "../roles/01_Nginx/vars/main.yml"
    - "../roles/01_Nginx/vars/{{ ansible_os_family }}.yml"
