---

- name: Playbook of 01_Nginx
  hosts:
    - nginx
  become: true
  roles:
    - role: '../roles/01_nginx'

  vars_files:
    - "../roles/01_nginx/vars/main.yml"
    - "../roles/01_nginx/vars/{{ ansible_os_family }}.yml"
