---

- name: Playbook of 001_bastion
  hosts:
    - bastions
  become: true
  roles:
    - { role: '001_bastion' }

- name: Playbook of 002_base
  hosts:
    - all
  become: true


- name: Playbook of 014_install_nftables
  hosts:
    - nodesweb
    - frontend
    - nodesdb
  become: true
  roles:
    - { role: '014_install_nftables' }


- name: Playbook of 000_start
  hosts:
    - all
  become: true
  roles:
    - { role: 003_haproxy_frontend, when: "'frontend' in group_names" }
    - { role: 004_backend_glusterfs, when: "'nodesweb' in group_names" }    
    - { role: 005_nginx_backend, when: "'nodesweb' in group_names" }
    - { role: 006_install_database_mysql, when: "'nodesdb' in group_names" }
    - { role: 007_install_proxysql, when: "'nodesweb' in group_names" }


- name: Playbook of 009_install_elk
  hosts:
    - nodeselk
  become: true
  roles:
    - { role: '009_install_elk' }


- name: Playbook of 010_install_filebeat
  hosts:
    - nodesweb
    - bastions
    - frontend
  become: true
  roles:
    - { role: '010_install_filebeat' }


- name: Playbook of "backupserver"
  hosts:
    - nodesbackup
  become: true
  roles:
    - role: '../roles/015_backupserver'


- name: Playbook of "dataservers"
  hosts:
    - frontend
    - nodesweb
    - nodesdb
  become: true
  roles:
    - role: '../roles/015_dataservers'    



- name: Playbook of 016_install_prometheus
  hosts:
    - nodesprom
  become: true
  roles:
    - { role: '016_install_prometheus' }


- name: Playbook of 017_install_grafana
  hosts:
    - nodesprom
  become: true
  roles:
    - { role: '017_install_grafana' }

- name: Playbook of "018_install_prometheus_nodeexporter"
  hosts:
    - all
  become: true
  roles:
    - role: '../roles/018_install_prometheus_nodeexporter'

  
      
