---

- name: Playbook of test_002
  hosts:
    - all
  become: true
  roles:
    - { role: 002_base }


- name: Playbook of test_003
  hosts:
    - frontend
  become: true
  roles:
    - { role: 003_nginx_frontend }

    
- name: Playbook of test_004
  hosts:
    - nodesweb
  become: true
  roles:
    - { role: 004_backend_glusterfs }    
  

- name: Playbook of test_005
  hosts:
    - nodesweb
  become: true
  roles:
    - { role: 005_nginx_backend }


- name: Playbook of 006_haproxybackend
  hosts:
    - nodeshaproxybackend
  become: true
  roles:
    - { role: '006_haproxybackend' }

- name: Playbook of 007_dcsbackend
  hosts:
    - nodesetcdbackend
  become: true
  roles:
    - { role: '007_dcsbackend' }


# - name: Playbook of 008_postgrespatroni
#   hosts:
#     - nodesdb
#   become: true
#   roles:
#     - { role: '008_postgrespatroni' }
