---

    ### NFT Stage

    - name: Install
      become: true
      package:
        name: nftables
        state: present

    - name: Set up configuration file
      become: true
      copy:
        src: templates/nftables.rules
        dest: "{{ nftables_config_file }}"
        owner: root
        group: root
        mode: 0644
      # '--check' is not available on current major distros. Disabling temporarily.
      #    validate: "nft --check --file %s"
      notify: reload nftables

    - name: Disable conflicting services
      become: true
      service:
        name: "{{ item }}"
        state: stopped
        enabled: no
      register: disable_service_result
      failed_when: (disable_service_result is failed) and ('Could not find the requested service' not in disable_service_result.msg)
      with_items:
        - iptables

    - name: Start service
      become: true
      service:
        name: nftables
        state: started
        daemon_reload: true

    - name: Enable service
      become: true
      service:
        name: nftables
        enabled: yes

    - name: Restarted service
      become: true
      service:
        name: nftables
        state: restarted
        daemon_reload: true
