---

- ansible.posix.sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: '1'
    sysctl_set: true
    state: present
    reload: true


- ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: Install keepalived package
  package:
    name: keepalived
    state: present

- name: Deploy haproxy configuration
  template:
    src: templates/keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: 0644
  tags:
    - config

- name: systemctl daemon-reload / start haproxy
  systemd:
    daemon_reload: yes
    name: keepalived
    state: restarted
    enabled: yes