---
wwwnginxuser: "nginxuser"
wwwnginxgroup: "www-data"
nginx_server_name: "{{ ansible_host }}"
nginx_www_folder: "/usr/share/nginx/html"
nginx_app_folder: "{{ nginx_www_folder }}/{{ nginx_server_name }}"

# WP
wp_version: 6.6.1
wp_install_dir: "{{ nginx_app_folder }}"
wp_db_name: "wordpress"
wp_db_user: "mysqluser"
wp_db_password: "mysqlpass"
#wp_db_host: "{{ ip_address['otus-nodedb-1-db'] }}"
wp_db_host: "10.110.0.50"
wp_db_charset: 'utf8'
wp_db_collate: ''
wp_table_prefix: 'wp_'
wp_debug: false
wp_admin_email: 'admin@example.com'
wp_webserver: nginx
site_name: "otus-6"



