---

- name: "Install gnupg"
  ansible.builtin.apt:
    name: gnupg2
    update_cache: yes

- name: "Install apt-transport-https"
  ansible.builtin.apt:
    name: apt-transport-https
    update_cache: yes

- name: Adds repository key
  apt_key:
    url: http://elasticrepo.serveradmin.ru/elastic.asc
    state: present

- name: Adds elastic alter repositories
  apt_repository:
    repo: 'deb http://elasticrepo.serveradmin.ru bookworm main'
    state: present

- name: Installs filebeat
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - filebeat

- name: restart filebeat
  systemd:
    name: filebeat
    state: restarted
    enabled: yes


- name: Copy filebeat-configuration file.
  template:
    src: "templates/filebeat.yml.j2"
    dest: /etc/filebeat/filebeat.yml 
    owner: root
    group: root
  become: true
  notify:
    - restart filebeat

- meta: flush_handlers
