---

- name: "Install gnupg"
  ansible.builtin.apt:
    name: gnupg2
    update_cache: yes

- name: "Install apt-transport-https"
  ansible.builtin.apt:
    name: apt-transport-https
    update_cache: yes

- name: Adds repository key
  apt_key:
    url: http://elasticrepo.serveradmin.ru/elastic.asc
    state: present

- name: Adds elastic alter repositories
  apt_repository:
    repo: 'deb http://elasticrepo.serveradmin.ru bookworm main'
    state: present

- name: Installs kibana
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - kibana

- name: restart kibana
  systemd:
    name: kibana
    state: restarted
    enabled: yes

#set kibana_password


- name: Reset kibana user password to random
  ansible.builtin.command: /usr/share/elasticsearch/bin/elasticsearch-reset-password -u kibana_system -b
  register: reset_cmd
  tags: passwordresetkibana

- name: Push password
  vars:
    my_tempkibana_password: "{{ reset_cmd.stdout_lines[-1]
      | regex_replace('^New value: (.*)$', '\\1') }}"
  ansible.builtin.uri:
    url: https://localhost:9200/_security/user/kibana_system/_password
    method: PUT
    url_username: kibana_system
    url_password: "{{ my_tempkibana_password}}"
    validate_certs: false
    body_format: json
    body:
      password: "{{ kibana_password }}"
    headers:
      Content-Type: "application/json"      
  tags: passwordresetkibana


# # set kibana config 

- name: Copy elastic-kibana ca file.
  copy:
    src: /etc/elasticsearch/certs
    dest: /etc/kibana
    owner: root
    group: kibana
    remote_src: true
  become: true
  notify:
    - restart kibana

- name: Copy elastic-configuration file.
  template:
    src: "templates/kibana.yml.j2"
    dest: /etc/kibana/kibana.yml
    owner: root
    group: kibana
    mode: 0660
  become: true
  notify:
    - restart kibana


