---
- name: install_elastic
  ansible.builtin.include_tasks: install_elastic.yml
  tags:
    - install_elastic
    - passwordreset

- name: install_kibana
  ansible.builtin.include_tasks: install_kibana.yml
  tags:
    - install_kibana
    - passwordresetkibana

- name: install_logstash
  ansible.builtin.include_tasks: install_logstash.yml
  tags:
    - install_logstash


# - name: install_filebeat
#   ansible.builtin.include_tasks: install_filebeat.yml
#   tags:
#     - install_filebeat
 