---
- meta: end_play
  when: (ansible_distribution != "CentOS")

#sed -i 's/^mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
#sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

- name: Install epel-release
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - epel-release

- name: Check Base Packages
  yum:
    name:         "{{ item.package }}"
    state:        "{{ item.state }}"
    update_cache: yes
  loop:
    - { package: "chrony",   state: "present" }
    - { package: "tree",   state: "present" }
    - { package: "tcpdump",   state: "present" }
    - { package: "bind-utils",   state: "present" }

- name: Set hostname
  hostname: 
    name: "{{ ansible_hostname }}"

# - name: Add my own IP address to /etc/hosts instead localhost
#   replace:
#     path: "/etc/hosts"
#     regexp: '^127\.0\.1\.1(\s+){{ ansible_hostname }}(\s+){{ ansible_hostname }}.*'
#     replace: "{{ ansible_host }} {{ ansible_hostname }} {{ ansible_hostname }}"

- name: Add node1 to /etc/hosts
  lineinfile:
    path: "/etc/hosts"
    state: present
    line: "10.100.0.10 otus-node-1"
  when: (ansible_hostname != "otus-node-1")

- name: Add node1 to /etc/hosts
  lineinfile:
    path: "/etc/hosts"
    state: present
    line: "10.100.0.11 otus-node-2"
  when: (ansible_hostname != "otus-node-2")

- name: Add node1 to /etc/hosts
  lineinfile:
    path: "/etc/hosts"
    state: present
    line: "10.100.0.12 otus-node-3"
  when: (ansible_hostname != "otus-node-3")
