---
# mysql root password
mysql_password: test2023!

# WP
wp_version: 5.0.3
wp_install_dir: "/usr/share/nginx/html"
wp_db_name: "wordpress"
wp_db_user: "mysqluser"
wp_db_password: "mysqlpass"
wp_db_host: "{{ ip_address['otus-nodedb-1-db'] }}"
wp_db_charset: 'utf8'
wp_db_collate: ''
wp_table_prefix: 'wp_'
wp_debug: false
wp_admin_email: 'admin@example.com'
wp_webserver: nginx
site_name: "otus-6"




