---

- name: Check Base Packages
  apt:
    name:         "{{ item.package }}"
    state:        "{{ item.state }}"
    update_cache: yes
  loop:
    - { package: "targetcli-fb",   state: "present" }


targetcli /backstores/block create disk01 /dev/vdb
targetcli /iscsi create iqn.2018-09.ru.otus:storage.target00
targetcli /iscsi/iqn.2018-09.ru.otus:storage.target00/tpg1/portals create 0.0.0.0
targetcli /iscsi/iqn.2018-09.ru.otus:storage.target00/tpg1/luns create /backstores/block/disk01 lun=1
targetcli /iscsi/iqn.2018-09.ru.otus:storage.target00/tpg1/luns ls lun1
targetcli /iscsi/iqn.2018-09.ru.otus:storage.target00/tpg1 set attribute authentication=0
targetcli /iscsi/iqn.2018-09.ru.otus:storage.target00/tpg1 /acls create iqn.1993-08.org.debian:01:9e3737c060bd
targetcli /iscsi/iqn.2018-09.ru.otus:storage.target00/tpg1 set parameter AuthMethod=CHAP
targetcli /iscsi/iqn.2018-09.ru.otus:storage.target00/tpg1 set auth userid=otus
targetcli /iscsi/iqn.2018-09.ru.otus:storage.target00/tpg1 set auth password=otus
