---

wwwnginxuser: "nginxuser"
wwwnginxgroup: "www-data"


nginx_listen_port: 80
nginx_listen_httpsport: 443
nginx_server_name: repoyc
web_dns: 8.8.8.8

nginx_config_template: "nginx.conf.j2"
nginx_repo_template: "repo.conf.j2"
nginx_index_template: "index.html"

# SSL Configuration
nginx_redirect_http_to_https: true
nginx_ssl_certificate: "/etc/nginx/ssl/{{ nginx_server_name }}.crt"
nginx_ssl_certificate_key: "/etc/nginx/ssl/{{ nginx_server_name }}.key"
nginx_ssl_protocols: "TLSv1.2 TLSv1.3"

# SSL Self-signed Certificate Configuration
nginx_create_self_signed_cert: true
nginx_self_signed_cert_subj: "/C=RU/ST=Moscow/L=Moscow/O=TECH/CN={{ nginx_server_name }}"




