---


- name: Check Base Packages
  yum:
    name:         "{{ item.package }}"
    state:        "{{ item.state }}"
    update_cache: yes
  loop:
    - { package: "device-mapper-multipath",   state: "present" }


- name: Creating MPIO config file
  command: "{{ item }}"
  with_items:
    - "/sbin/mpathconf --enable"
  notify: "restart multipathd"